[workspace]
resolver = "2"
members = ["crates/spool-core", "crates/spool-nntp", "crates/spool"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[profile.release]
opt-level = 3
lto = "thin"
strip = true

[profile.dev.package."*"]
opt-level = 2

[profile.dev]
debug = 0
